# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Unplug' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Unplug

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'	
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
end
